In [1]:
##kitabxan idxali ve fayli oxu,a
import pandas as pd
customer_data = pd.read_csv("customer_data_50.csv")
customer_data.head()

,customer_id,first_name,last_name,email,gender,age,city,state,country,purchase_count,total_spend,avg_order_value,last_purchase_date
0,1001,Sophia,Smith,sophia.smith@example.com,M,54,San Antonio,TX,USA,5,965,193.0,2023-09-12 15:28:32.140488
1,1002,Joseph,Smith,joseph.smith@example.com,M,66,Los Angeles,CA,USA,7,1246,178.0,2023-08-25 15:28:32.140488
2,1003,John,Anderson,john.anderson@example.com,F,56,Phoenix,AZ,USA,1,199,199.0,2024-04-28 15:28:32.140488
3,1004,Emma,Hernandez,emma.hernandez@example.com,M,44,Los Angeles,CA,USA,14,3752,268.0,2024-01-01 15:28:32.140488
4,1005,Emily,Garcia,emily.garcia@example.com,F,25,Dallas,TX,USA,12,1620,135.0,2023-12-09 15:28:32.140488

In [2]:
#setir ve sutun sayi
customer_data.shape

(50, 13)

In [6]:
#sutunlar haqqinda melumatlar
print(customer_data.info())

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         50 non-null     int64
 1   first_name          50 non-null     str
 2   last_name           50 non-null     str
 3   email               50 non-null     str
 4   gender              50 non-null     str
 5   age                 50 non-null     int64
 6   city                50 non-null     str
 7   state               50 non-null     str
 8   country             50 non-null     str
 9   purchase_count      50 non-null     int64
 10  total_spend         50 non-null     int64
 11  avg_order_value     50 non-null     float64
 12  last_purchase_date  50 non-null     str
dtypes: float64(1), int64(4), str(8)
memory usage: 5.2 KB
None

In [5]:
#statistika|
print(customer_data.describe())

       customer_id        age  purchase_count  total_spend  avg_order_value
count     50.00000  50.000000        50.00000    50.000000        50.000000
mean    1025.50000  43.440000         8.60000  1491.880000       179.920000
std       14.57738  14.833993         4.28095   968.697666        70.820221
min     1001.00000  19.000000         1.00000   199.000000        53.000000
25%     1013.25000  30.000000         5.00000   819.000000       125.750000
50%     1025.50000  44.500000         8.00000  1350.000000       180.000000
75%     1037.75000  54.000000        12.00000  1916.000000       237.500000
max     1050.00000  69.000000        15.00000  4440.000000       299.000000

In [4]:
#ortalama
mean_age=customer_data["age"].mean()
print(mean_age)

43.44

In [3]:
#median
median_age=customer_data["age"].median()
print(median_age)

44.5

In [9]:
#musteri sayi
customer_count = customer_data.shape[0]
print(customer_count)
customer_count = len(customer_data)
print(customer_count)

50
50

In [10]:
#sutun sayi
columns_count=customer_data.shape[1]
print(columns_count)

13

In [12]:
#yas ortalamasi
age_average=customer_data["age"].mean()
print(age_average)

43.44

In [14]:
#en yasli musteri yasi
old_age=customer_data["age"].max()
print(old_age)

69

In [16]:
older_50=customer_data[customer_data["age"]>50]
older_50.head()

,customer_id,first_name,last_name,email,gender,age,city,state,country,purchase_count,total_spend,avg_order_value,last_purchase_date
0,1001,Sophia,Smith,sophia.smith@example.com,M,54,San Antonio,TX,USA,5,965,193.0,2023-09-12 15:28:32.140488
1,1002,Joseph,Smith,joseph.smith@example.com,M,66,Los Angeles,CA,USA,7,1246,178.0,2023-08-25 15:28:32.140488
2,1003,John,Anderson,john.anderson@example.com,F,56,Phoenix,AZ,USA,1,199,199.0,2024-04-28 15:28:32.140488
5,1006,Ava,Taylor,ava.taylor@example.com,F,69,San Jose,CA,USA,14,1792,128.0,2024-03-13 15:28:32.140488
6,1007,Jane,Martinez,jane.martinez@example.com,F,63,New York,NY,USA,3,804,268.0,2024-03-27 15:28:32.140488

In [17]:
#2000 den cox pul xercleyenler
spent_2000=customer_data[customer_data["total_spend"]>2000]
spent_2000.head()

,customer_id,first_name,last_name,email,gender,age,city,state,country,purchase_count,total_spend,avg_order_value,last_purchase_date
3,1004,Emma,Hernandez,emma.hernandez@example.com,M,44,Los Angeles,CA,USA,14,3752,268.0,2024-01-01 15:28:32.140488
8,1009,David,Davis,david.davis@example.com,F,59,Phoenix,AZ,USA,14,3304,236.0,2024-08-17 15:28:32.140488
12,1013,Sophia,Thomas,sophia.thomas@example.com,F,29,New York,NY,USA,15,4440,296.0,2024-05-28 15:28:32.140488
13,1014,Emma,Martinez,emma.martinez@example.com,F,45,Phoenix,AZ,USA,15,2190,146.0,2024-06-16 15:28:32.140488
30,1031,Mia,Moore,mia.moore@example.com,F,53,Phoenix,AZ,USA,12,2304,192.0,2023-12-30 15:28:32.140488

In [18]:
#10 ve daha cox musteri satanlar
customers_10_orders=customer_data[customer_data["purchase_count"]>=10]
customers_10_orders.head()

,customer_id,first_name,last_name,email,gender,age,city,state,country,purchase_count,total_spend,avg_order_value,last_purchase_date
3,1004,Emma,Hernandez,emma.hernandez@example.com,M,44,Los Angeles,CA,USA,14,3752,268.0,2024-01-01 15:28:32.140488
4,1005,Emily,Garcia,emily.garcia@example.com,F,25,Dallas,TX,USA,12,1620,135.0,2023-12-09 15:28:32.140488
5,1006,Ava,Taylor,ava.taylor@example.com,F,69,San Jose,CA,USA,14,1792,128.0,2024-03-13 15:28:32.140488
8,1009,David,Davis,david.davis@example.com,F,59,Phoenix,AZ,USA,14,3304,236.0,2024-08-17 15:28:32.140488
10,1011,Mia,Taylor,mia.taylor@example.com,F,24,Houston,TX,USA,15,1020,68.0,2024-06-17 15:28:32.140488

In [22]:
#en cox xercleyen 5 musteri
customer_data["total_spend"].sort_values(ascending=False).head(5)
customer_data.sort_values("total_spend", ascending=False).head(5)

,customer_id,first_name,last_name,email,gender,age,city,state,country,purchase_count,total_spend,avg_order_value,last_purchase_date
12,1013,Sophia,Thomas,sophia.thomas@example.com,F,29,New York,NY,USA,15,4440,296.0,2024-05-28 15:28:32.140488
3,1004,Emma,Hernandez,emma.hernandez@example.com,M,44,Los Angeles,CA,USA,14,3752,268.0,2024-01-01 15:28:32.140488
41,1042,Ava,Moore,ava.moore@example.com,M,20,San Diego,CA,USA,15,3345,223.0,2023-12-01 15:28:32.140488
8,1009,David,Davis,david.davis@example.com,F,59,Phoenix,AZ,USA,14,3304,236.0,2024-08-17 15:28:32.140488
42,1043,Michael,Jackson,michael.jackson@example.com,F,31,San Diego,CA,USA,13,3159,243.0,2024-03-24 15:28:32.140488

In [24]:
customer_data.sort_values("age").head()

,customer_id,first_name,last_name,email,gender,age,city,state,country,purchase_count,total_spend,avg_order_value,last_purchase_date
19,1020,Abigail,Jones,abigail.jones@example.com,F,19,Houston,TX,USA,1,262,262.0,2023-11-15 15:28:32.140488
32,1033,Charlotte,Taylor,charlotte.taylor@example.com,M,20,San Diego,CA,USA,2,562,281.0,2023-11-15 15:28:32.140488
41,1042,Ava,Moore,ava.moore@example.com,M,20,San Diego,CA,USA,15,3345,223.0,2023-12-01 15:28:32.140488
39,1040,Matthew,Garcia,matthew.garcia@example.com,F,23,Philadelphia,PA,USA,7,1939,277.0,2024-03-09 15:28:32.140488
48,1049,Emma,Jones,emma.jones@example.com,F,23,Chicago,IL,USA,10,780,78.0,2024-02-18 15:28:32.140488

In [25]:
customer_data.groupby("city").size()

city
Chicago         2
Dallas          3
Houston         5
Los Angeles     7
New York        4
Philadelphia    2
Phoenix         8
San Antonio     2
San Diego       8
San Jose        9
dtype: int64

In [27]:
# Şəhərlər üzrə ümumi xərcləməni hesablayırıq
customer_data.groupby("city")["total_spend"].sum()

city
Chicago          2496
Dallas           4929
Houston          3626
Los Angeles     10946
New York         7574
Philadelphia     2319
Phoenix         12859
San Antonio      2885
San Diego       13098
San Jose        13862
Name: total_spend, dtype: int64

In [30]:
# Cins üzrə müştəri sayını tapırıq
customer_data["gender"].value_counts()

gender
M    27
F    23
Name: count, dtype: int64